### ISSUE TITLE
iOS 12 crash

### ISSUE THREAD

**Issue by dklt** [matmartinez/MMNumberKeyboard#39] opened 2018-07-16 03:49 UTC
Hi,

Reporting...
iOS12b3 seems crash at this macro,

@ MMNumberKeyboard.m

#define UIKitLocalizedString(key) [[NSBundle bundleWithIdentifier:@"com.apple.UIKit"] localizedStringForKey:key value:@"" table:nil]

**_Reproduce-able on device w/iOS12b3 and XCode10b3_**

**Comment by vincentneo** [comment] 2018-09-28 13:34
I have tested with the example app, on release versions of iOS 12, and Xcode 10, but was unable to reproduce the error.

**Comment by matmartinez** [comment] 2018-10-01 13:41
Cannot reproduce the issue. Closing this now.

**Closed by matmartinez** 2018-10-01 13:41 UTC
