### ISSUE TITLE
Keyboard always shows in Simulator

### ISSUE THREAD

**Issue by tomlokhorst** [matmartinez/MMNumberKeyboard#14] opened 2016-03-30 12:41 UTC
In the iOS Simulator, the keyboard always show up, even when set to "Connect Hardware Keyboard".
The same is true when connecting a bluetooth keyboard to a physical iPhone.

It would be nice if this number keyboard only shows up when a software keyboard is needed.

Great library btw, this keyboard is very nice.

**Comment by matmartinez** [comment] 2016-03-30 21:46
Hey tomlokhorst, 

This is expected behavior on UIKit. If you *don't want* to display an `inputView` (or an `inputAccessoryView`) when a keyboard is connected, then you must set to `nil` the `-inputView` accordingly.

UIKit will post the `UIKeyboardWillShowNotification` notification **only if an external keyboard is not present**.

With that in mind a little work, you should be able to update your first responder to use   `MMNumberKeyboard` only when necessary.

I'll be closing this issue because this level of customization should be addressed in your code. Have a good one!
Matías.

**Closed by matmartinez** 2016-03-30 21:46 UTC
